// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkjesciiyfftwoflwlln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdramVzY2lpeWZmdHdvZmx3bGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyOTgyNzYsImV4cCI6MjA2MDg3NDI3Nn0.cWeDOG4vsI4_z64BzCWSm2rEB6OIvTMMVC-WRqyZpGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);